# Partitioning configuration for Calamares

---
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs", "f2fs"]

enableEncryption: false

drawNestedPartitions: false
alwaysShowPartitionLabels: true
defaultMountOptions:
  - defaults

initialSwapChoice: "none"

allowManualPartitioning: true
