---
modules-search: [local, /usr/lib/calamares/modules]

instances:
  - id: setshell
    module: shellprocess
    config: shellprocess-setshell.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - users
      - shellprocess@setshell
      - removeuser
      - displaymanager
      - networkcfg
      - hwclock
      - services-runit
      - packages
      - dracut
      - grubcfg
      - bootloader
      - umount
  - show:
      - finished

branding: lyargoos

oem-setup: false

dont-chroot: false

prompt-install: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
