---
modules-search: [local, /usr/lib/calamares/modules]

instances:
  - id: createuser
    module: users
    config: users.conf
  - id: setuser
    module: setuser
    config: users.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - pkgchooser
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - fstab
      - localecfg
      - users/createuser
      - displaymanager
      - networkcfg
      - hwclock
      - services-runit
      - packages
      - grubcfg
  - finish:
      - umount
      - summary

oem-setup: false

dont-chroot: false

prompt-install: false
