---
dontChroot: false
timeout: 10

script:
    # Set zsh as default shell for the created user
    - command: "chsh -s /bin/zsh ${USER}"
    # Set zsh as default shell for root
    - command: "chsh -s /bin/zsh root"

i18n:
    name: "Set default shell to zsh"
