---
unpack:
    - source: /run/rootfsbase
      sourcefs: ext3
      destination: ""
      exclude:
          - "etc/motd"
          - "etc/issue"
          - "etc/sddm.conf"
          - "etc/calamares"
          - "etc/sudoers.d/99-lyargoos-live"
          - "etc/skel/Desktop/calamares.desktop"
          - "home/live"
          - "var/cache/xbps"
