# User creation configuration for Calamares

---
defaultGroups:
  - users
  - wheel
  - audio
  - video
  - network
  - plugdev

autologinGroup: autologin
doAutologin: true

setRootPassword: true
doReusePassword: true

passwordRequirements:
  minLength: -1
  maxLength: -1

forbidPasswords:
  - root
  - admin
  - password
